apiVersion: v1
kind: Service
metadata:
  name: cloud-mgmt-service
spec:
  type: NodePort
  ports:
    - port: 9002
      targetPort: 9000
      nodePort: 30002
      protocol: TCP
      name: http
  selector:
    name: cloud-mgmt-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-mgmt-service-deployment
spec:
  selector:
    matchLabels:
      name: cloud-mgmt-service
  replicas: 1
  template:
    metadata:
      labels:
        name: cloud-mgmt-service
      annotations:
        iam.amazonaws.com/role: cratekube-worker-node-role
    spec:
      containers:
        - name: cloud-mgmt-service
          image: cratekube/cloud-mgmt-service:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /app/kube/cratekube_rsa.pub
              name: public-key-volume
            - mountPath: /app/config/
              name: config-volume
          env:
            - name: SSH_PUBLIC_KEY_PATH
              value: /app/kube/cratekube_rsa.pub
            - name: ADMIN_APIKEY
              valueFrom:
                secretKeyRef:
                  name: cratekube-api-secret
                  key: admin-api-key
      volumes:
        - name: public-key-volume
          hostPath:
            path: /var/lib/cratekube/cratekube_rsa.pub
        - name: config-volume
          hostPath:
            path: /var/lib/cratekube/cloud-mgmt-service/config/
